# Generated by Django 4.1.7 on 2023-03-03 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('qid', models.TextField(primary_key=True, serialize=False)),
                ('question', models.TextField()),
                ('options', models.TextField()),
                ('q_image', models.TextField()),
                ('answer_q', models.TextField()),
                ('subject', models.TextField()),
                ('contain_img', models.BooleanField()),
            ],
            options={
                'db_table': 'mcqs',
            },
        ),
    ]
