# Generated by Django 4.1.7 on 2023-03-03 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mcq',
            name='img_file',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
