# Generated by Django 4.1.7 on 2023-03-03 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0002_mcq_img_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='answer_q',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='q_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question',
            field=models.TextField(blank=True, null=True),
        ),
    ]
