# Generated by Django 4.1.7 on 2023-03-03 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0003_alter_mcq_answer_q_alter_mcq_q_image_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mcq',
            table=None,
        ),
    ]
