# Generated by Django 4.1.7 on 2023-03-06 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbank', '0004_alter_mcq_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='mcq',
            table='mcqs',
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('subject', models.TextField(primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(default='admin', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username')),
            ],
        ),
    ]
