# Generated by Django 4.1.7 on 2023-03-06 08:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('questionbank', '0007_permission_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Permission',
            new_name='SubjectAccess',
        ),
    ]
