# Generated by Django 4.1.7 on 2023-03-18 04:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0008_rename_permission_subjectaccess'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='subject',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questionbank.subject'),
        ),
    ]
