# Generated by Django 4.1.7 on 2023-03-18 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0009_alter_mcq_subject'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='answer_q',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='options',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='q_image',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
