# Generated by Django 4.1.7 on 2023-03-19 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questionbank', '0011_alter_mcq_qid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='answer_q',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='options',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='q_image',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
